///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class YoutubePlaylistPageInfo {
/*
{
  "totalResults": 6,
  "resultsPerPage": 10
}
*/

  int? totalResults;
  int? resultsPerPage;

  YoutubePlaylistPageInfo({
    this.totalResults,
    this.resultsPerPage,
  });
  YoutubePlaylistPageInfo.fromJson(Map<String, dynamic> json) {
    totalResults = json['totalResults']?.toInt();
    resultsPerPage = json['resultsPerPage']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['totalResults'] = totalResults;
    data['resultsPerPage'] = resultsPerPage;
    return data;
  }
}

class YoutubePlaylistItemsSnippetResourceId {
/*
{
  "kind": "youtube#video",
  "videoId": "F0Cg05TVRkg"
}
*/

  String? kind;
  String? videoId;

  YoutubePlaylistItemsSnippetResourceId({
    this.kind,
    this.videoId,
  });
  YoutubePlaylistItemsSnippetResourceId.fromJson(Map<String, dynamic> json) {
    kind = json['kind']?.toString();
    videoId = json['videoId']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['kind'] = kind;
    data['videoId'] = videoId;
    return data;
  }
}

class YoutubePlaylistItemsSnippetThumbnailsMaxres {
/*
{
  "url": "https://i.ytimg.com/vi/F0Cg05TVRkg/maxresdefault.jpg",
  "width": 1280,
  "height": 720
}
*/

  String? url;
  int? width;
  int? height;

  YoutubePlaylistItemsSnippetThumbnailsMaxres({
    this.url,
    this.width,
    this.height,
  });
  YoutubePlaylistItemsSnippetThumbnailsMaxres.fromJson(Map<String, dynamic> json) {
    url = json['url']?.toString();
    width = json['width']?.toInt();
    height = json['height']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['url'] = url;
    data['width'] = width;
    data['height'] = height;
    return data;
  }
}

class YoutubePlaylistItemsSnippetThumbnailsStandard {
/*
{
  "url": "https://i.ytimg.com/vi/F0Cg05TVRkg/sddefault.jpg",
  "width": 640,
  "height": 480
}
*/

  String? url;
  int? width;
  int? height;

  YoutubePlaylistItemsSnippetThumbnailsStandard({
    this.url,
    this.width,
    this.height,
  });
  YoutubePlaylistItemsSnippetThumbnailsStandard.fromJson(Map<String, dynamic> json) {
    url = json['url']?.toString();
    width = json['width']?.toInt();
    height = json['height']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['url'] = url;
    data['width'] = width;
    data['height'] = height;
    return data;
  }
}

class YoutubePlaylistItemsSnippetThumbnailsHigh {
/*
{
  "url": "https://i.ytimg.com/vi/F0Cg05TVRkg/hqdefault.jpg",
  "width": 480,
  "height": 360
}
*/

  String? url;
  int? width;
  int? height;

  YoutubePlaylistItemsSnippetThumbnailsHigh({
    this.url,
    this.width,
    this.height,
  });
  YoutubePlaylistItemsSnippetThumbnailsHigh.fromJson(Map<String, dynamic> json) {
    url = json['url']?.toString();
    width = json['width']?.toInt();
    height = json['height']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['url'] = url;
    data['width'] = width;
    data['height'] = height;
    return data;
  }
}

class YoutubePlaylistItemsSnippetThumbnailsMedium {
/*
{
  "url": "https://i.ytimg.com/vi/F0Cg05TVRkg/mqdefault.jpg",
  "width": 320,
  "height": 180
}
*/

  String? url;
  int? width;
  int? height;

  YoutubePlaylistItemsSnippetThumbnailsMedium({
    this.url,
    this.width,
    this.height,
  });
  YoutubePlaylistItemsSnippetThumbnailsMedium.fromJson(Map<String, dynamic> json) {
    url = json['url']?.toString();
    width = json['width']?.toInt();
    height = json['height']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['url'] = url;
    data['width'] = width;
    data['height'] = height;
    return data;
  }
}

class YoutubePlaylistItemsSnippetThumbnailsDefault {
/*
{
  "url": "https://i.ytimg.com/vi/F0Cg05TVRkg/default.jpg",
  "width": 120,
  "height": 90
}
*/

  String? url;
  int? width;
  int? height;

  YoutubePlaylistItemsSnippetThumbnailsDefault({
    this.url,
    this.width,
    this.height,
  });
  YoutubePlaylistItemsSnippetThumbnailsDefault.fromJson(Map<String, dynamic> json) {
    url = json['url']?.toString();
    width = json['width']?.toInt();
    height = json['height']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['url'] = url;
    data['width'] = width;
    data['height'] = height;
    return data;
  }
}

class YoutubePlaylistItemsSnippetThumbnails {
/*
{
  "default": {
    "url": "https://i.ytimg.com/vi/F0Cg05TVRkg/default.jpg",
    "width": 120,
    "height": 90
  },
  "medium": {
    "url": "https://i.ytimg.com/vi/F0Cg05TVRkg/mqdefault.jpg",
    "width": 320,
    "height": 180
  },
  "high": {
    "url": "https://i.ytimg.com/vi/F0Cg05TVRkg/hqdefault.jpg",
    "width": 480,
    "height": 360
  },
  "standard": {
    "url": "https://i.ytimg.com/vi/F0Cg05TVRkg/sddefault.jpg",
    "width": 640,
    "height": 480
  },
  "maxres": {
    "url": "https://i.ytimg.com/vi/F0Cg05TVRkg/maxresdefault.jpg",
    "width": 1280,
    "height": 720
  }
}
*/

  YoutubePlaylistItemsSnippetThumbnailsDefault? theDefault;
  YoutubePlaylistItemsSnippetThumbnailsMedium? medium;
  YoutubePlaylistItemsSnippetThumbnailsHigh? high;
  YoutubePlaylistItemsSnippetThumbnailsStandard? standard;
  YoutubePlaylistItemsSnippetThumbnailsMaxres? maxres;

  YoutubePlaylistItemsSnippetThumbnails({
    this.theDefault,
    this.medium,
    this.high,
    this.standard,
    this.maxres,
  });
  YoutubePlaylistItemsSnippetThumbnails.fromJson(Map<String, dynamic> json) {
    theDefault = (json['default'] != null) ? YoutubePlaylistItemsSnippetThumbnailsDefault.fromJson(json['default']) : null;
    medium = (json['medium'] != null) ? YoutubePlaylistItemsSnippetThumbnailsMedium.fromJson(json['medium']) : null;
    high = (json['high'] != null) ? YoutubePlaylistItemsSnippetThumbnailsHigh.fromJson(json['high']) : null;
    standard = (json['standard'] != null) ? YoutubePlaylistItemsSnippetThumbnailsStandard.fromJson(json['standard']) : null;
    maxres = (json['maxres'] != null) ? YoutubePlaylistItemsSnippetThumbnailsMaxres.fromJson(json['maxres']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (theDefault != null) {
      data['default'] = theDefault!.toJson();
    }
    if (medium != null) {
      data['medium'] = medium!.toJson();
    }
    if (high != null) {
      data['high'] = high!.toJson();
    }
    if (standard != null) {
      data['standard'] = standard!.toJson();
    }
    if (maxres != null) {
      data['maxres'] = maxres!.toJson();
    }
    return data;
  }
}

class YoutubePlaylistItemsSnippet {
/*
{
  "publishedAt": "2022-12-19T15:35:08Z",
  "channelId": "UCjCiV0FJxYLhrIMbKVpxf6w",
  "title": "Rompiendo esquemas con Wendy La Rosa",
  "description": "¡Estamos de estreno!\n\nEn este primer capitulo de  ''Rompiendo esquemas'' escucharas curiosidades del mundo de las mujeres y su papel en la historia, ciencia, tecnología y música. \n\nLa cita es todos los jueves a través de www.mujeresradio.net....Ideal par nosotras!",
  "thumbnails": {
    "default": {
      "url": "https://i.ytimg.com/vi/F0Cg05TVRkg/default.jpg",
      "width": 120,
      "height": 90
    },
    "medium": {
      "url": "https://i.ytimg.com/vi/F0Cg05TVRkg/mqdefault.jpg",
      "width": 320,
      "height": 180
    },
    "high": {
      "url": "https://i.ytimg.com/vi/F0Cg05TVRkg/hqdefault.jpg",
      "width": 480,
      "height": 360
    },
    "standard": {
      "url": "https://i.ytimg.com/vi/F0Cg05TVRkg/sddefault.jpg",
      "width": 640,
      "height": 480
    },
    "maxres": {
      "url": "https://i.ytimg.com/vi/F0Cg05TVRkg/maxresdefault.jpg",
      "width": 1280,
      "height": 720
    }
  },
  "channelTitle": "Mujeres Radio",
  "playlistId": "PL1SAh140OrrNKYRI4YCGnN2ZcrdGh2wps",
  "position": 0,
  "resourceId": {
    "kind": "youtube#video",
    "videoId": "F0Cg05TVRkg"
  },
  "videoOwnerChannelTitle": "Mujeres Radio",
  "videoOwnerChannelId": "UCjCiV0FJxYLhrIMbKVpxf6w"
}
*/

  String? publishedAt;
  String? channelId;
  String? title;
  String? description;
  YoutubePlaylistItemsSnippetThumbnails? thumbnails;
  String? channelTitle;
  String? playlistId;
  int? position;
  YoutubePlaylistItemsSnippetResourceId? resourceId;
  String? videoOwnerChannelTitle;
  String? videoOwnerChannelId;

  YoutubePlaylistItemsSnippet({
    this.publishedAt,
    this.channelId,
    this.title,
    this.description,
    this.thumbnails,
    this.channelTitle,
    this.playlistId,
    this.position,
    this.resourceId,
    this.videoOwnerChannelTitle,
    this.videoOwnerChannelId,
  });
  YoutubePlaylistItemsSnippet.fromJson(Map<String, dynamic> json) {
    publishedAt = json['publishedAt']?.toString();
    channelId = json['channelId']?.toString();
    title = json['title']?.toString();
    description = json['description']?.toString();
    thumbnails = (json['thumbnails'] != null) ? YoutubePlaylistItemsSnippetThumbnails.fromJson(json['thumbnails']) : null;
    channelTitle = json['channelTitle']?.toString();
    playlistId = json['playlistId']?.toString();
    position = json['position']?.toInt();
    resourceId = (json['resourceId'] != null) ? YoutubePlaylistItemsSnippetResourceId.fromJson(json['resourceId']) : null;
    videoOwnerChannelTitle = json['videoOwnerChannelTitle']?.toString();
    videoOwnerChannelId = json['videoOwnerChannelId']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['publishedAt'] = publishedAt;
    data['channelId'] = channelId;
    data['title'] = title;
    data['description'] = description;
    if (thumbnails != null) {
      data['thumbnails'] = thumbnails!.toJson();
    }
    data['channelTitle'] = channelTitle;
    data['playlistId'] = playlistId;
    data['position'] = position;
    if (resourceId != null) {
      data['resourceId'] = resourceId!.toJson();
    }
    data['videoOwnerChannelTitle'] = videoOwnerChannelTitle;
    data['videoOwnerChannelId'] = videoOwnerChannelId;
    return data;
  }
}

class YoutubePlaylistItems {
/*
{
  "kind": "youtube#playlistItem",
  "etag": "JqJ-VorXkSZmqdKVd9VY-tIOvos",
  "id": "UEwxU0FoMTQwT3JyTktZUkk0WUNHbk4yWmNyZEdoMndwcy41NkI0NEY2RDEwNTU3Q0M2",
  "snippet": {
    "publishedAt": "2022-12-19T15:35:08Z",
    "channelId": "UCjCiV0FJxYLhrIMbKVpxf6w",
    "title": "Rompiendo esquemas con Wendy La Rosa",
    "description": "¡Estamos de estreno!\n\nEn este primer capitulo de  ''Rompiendo esquemas'' escucharas curiosidades del mundo de las mujeres y su papel en la historia, ciencia, tecnología y música. \n\nLa cita es todos los jueves a través de www.mujeresradio.net....Ideal par nosotras!",
    "thumbnails": {
      "default": {
        "url": "https://i.ytimg.com/vi/F0Cg05TVRkg/default.jpg",
        "width": 120,
        "height": 90
      },
      "medium": {
        "url": "https://i.ytimg.com/vi/F0Cg05TVRkg/mqdefault.jpg",
        "width": 320,
        "height": 180
      },
      "high": {
        "url": "https://i.ytimg.com/vi/F0Cg05TVRkg/hqdefault.jpg",
        "width": 480,
        "height": 360
      },
      "standard": {
        "url": "https://i.ytimg.com/vi/F0Cg05TVRkg/sddefault.jpg",
        "width": 640,
        "height": 480
      },
      "maxres": {
        "url": "https://i.ytimg.com/vi/F0Cg05TVRkg/maxresdefault.jpg",
        "width": 1280,
        "height": 720
      }
    },
    "channelTitle": "Mujeres Radio",
    "playlistId": "PL1SAh140OrrNKYRI4YCGnN2ZcrdGh2wps",
    "position": 0,
    "resourceId": {
      "kind": "youtube#video",
      "videoId": "F0Cg05TVRkg"
    },
    "videoOwnerChannelTitle": "Mujeres Radio",
    "videoOwnerChannelId": "UCjCiV0FJxYLhrIMbKVpxf6w"
  }
}
*/

  String? kind;
  String? etag;
  String? id;
  YoutubePlaylistItemsSnippet? snippet;

  YoutubePlaylistItems({
    this.kind,
    this.etag,
    this.id,
    this.snippet,
  });
  YoutubePlaylistItems.fromJson(Map<String, dynamic> json) {
    kind = json['kind']?.toString();
    etag = json['etag']?.toString();
    id = json['id']?.toString();
    snippet = (json['snippet'] != null) ? YoutubePlaylistItemsSnippet.fromJson(json['snippet']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['kind'] = kind;
    data['etag'] = etag;
    data['id'] = id;
    if (snippet != null) {
      data['snippet'] = snippet!.toJson();
    }
    return data;
  }
}

class YoutubePlaylist {
/*
{
  "kind": "youtube#playlistItemListResponse",
  "etag": "y5evZ_oAP_OqL-aUg7uryVqtXQo",
  "items": [
    {
      "kind": "youtube#playlistItem",
      "etag": "JqJ-VorXkSZmqdKVd9VY-tIOvos",
      "id": "UEwxU0FoMTQwT3JyTktZUkk0WUNHbk4yWmNyZEdoMndwcy41NkI0NEY2RDEwNTU3Q0M2",
      "snippet": {
        "publishedAt": "2022-12-19T15:35:08Z",
        "channelId": "UCjCiV0FJxYLhrIMbKVpxf6w",
        "title": "Rompiendo esquemas con Wendy La Rosa",
        "description": "¡Estamos de estreno!\n\nEn este primer capitulo de  ''Rompiendo esquemas'' escucharas curiosidades del mundo de las mujeres y su papel en la historia, ciencia, tecnología y música. \n\nLa cita es todos los jueves a través de www.mujeresradio.net....Ideal par nosotras!",
        "thumbnails": {
          "default": {
            "url": "https://i.ytimg.com/vi/F0Cg05TVRkg/default.jpg",
            "width": 120,
            "height": 90
          },
          "medium": {
            "url": "https://i.ytimg.com/vi/F0Cg05TVRkg/mqdefault.jpg",
            "width": 320,
            "height": 180
          },
          "high": {
            "url": "https://i.ytimg.com/vi/F0Cg05TVRkg/hqdefault.jpg",
            "width": 480,
            "height": 360
          },
          "standard": {
            "url": "https://i.ytimg.com/vi/F0Cg05TVRkg/sddefault.jpg",
            "width": 640,
            "height": 480
          },
          "maxres": {
            "url": "https://i.ytimg.com/vi/F0Cg05TVRkg/maxresdefault.jpg",
            "width": 1280,
            "height": 720
          }
        },
        "channelTitle": "Mujeres Radio",
        "playlistId": "PL1SAh140OrrNKYRI4YCGnN2ZcrdGh2wps",
        "position": 0,
        "resourceId": {
          "kind": "youtube#video",
          "videoId": "F0Cg05TVRkg"
        },
        "videoOwnerChannelTitle": "Mujeres Radio",
        "videoOwnerChannelId": "UCjCiV0FJxYLhrIMbKVpxf6w"
      }
    }
  ],
  "pageInfo": {
    "totalResults": 6,
    "resultsPerPage": 10
  }
}
*/

  String? kind;
  String? etag;
  List<YoutubePlaylistItems?>? items;
  YoutubePlaylistPageInfo? pageInfo;

  YoutubePlaylist({
    this.kind,
    this.etag,
    this.items,
    this.pageInfo,
  });
  YoutubePlaylist.fromJson(Map<String, dynamic> json) {
    kind = json['kind']?.toString();
    etag = json['etag']?.toString();
    if (json['items'] != null) {
      final v = json['items'];
      final arr0 = <YoutubePlaylistItems>[];
      v.forEach((v) {
        arr0.add(YoutubePlaylistItems.fromJson(v));
      });
      items = arr0;
    }
    pageInfo = (json['pageInfo'] != null) ? YoutubePlaylistPageInfo.fromJson(json['pageInfo']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['kind'] = kind;
    data['etag'] = etag;
    if (items != null) {
      final v = items;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['items'] = arr0;
    }
    if (pageInfo != null) {
      data['pageInfo'] = pageInfo!.toJson();
    }
    return data;
  }
}
